name: 'SBOM Generation and Scanning'
description: 'Generates a Software Bill of MAterials (SBOM) and scans for known vulnerabilities failing on any critical vulns
author: 'xKingPanda@'
outputs:
  sbom-file:
    description: 'The syft generated SBOM'
    value: ${{ steps.sbom-gen-and-scane.outputs.sbom-file }}
runs:
  using: 'docker'
  image: 'Dockerfile'
