name: 'Terraformer'
description: 'Executes terraform plan and apply steps'
author: 'xKingPanda'
inputs:
  ARM_CLIENT_ID:
    description: 'The Azure Client ID'
    required: true
  ARM_CLIENT_SECRET:
    description: 'The Azure Client Secret'
    required: true
  ARM_SUBSCRIPTION_ID:
    description: 'The Azure Subscription'
    required: true
  ARM_TENANT_ID:
    description: 'The Azure Tenant ID' 
    required: true
  STATE_KEY: 
    description: 'The Unique Key for State Lookup'
    required: true
  TF_STAGE:
    description: 'The Terraform Deployment Stage'
    required: true
  DJANGO_SECRET_KEY_PROD:
    description: 'The secret key for django to startup'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  
