name: Build-Curl
on:
  workflow_dispatch
permissions: {}
jobs: 
  build-and-curl:
    runs-on: ubuntu-latest
    steps:
    - name: get_code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: docker_build
      run: |
        docker build -t pipeline-test .
    - name: docker_run
      run: |
        docker run -d -p 8000:8000 --env-file .env pipeline-test
    - name: curl_ftw
      run: |
        sleep 10
        curl -f http://localhost:8000/
